using Analyst.DBAccess.Contexts;
using Analyst.Domain;
using Analyst.Domain.Edgar;
using Analyst.Domain.Edgar.Datasets;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Analyst.Services
{
    /// <summary>
    /// Esta clase es un asco y esta toda hardcodeada, pero lo que tiene va a cambiar casi nunca
    /// TODO: algunas cosas hay que parametrizarlas
    /// </summary>
    public class InitialLoader
    {

        internal static void LoadInitialDatasets(IAnalystRepository repository)
        {
            string baseurl = "/files/dera/data/financial-statement-and-notes-data-sets";
            List<EdgarDataset> datasets = new List<EdgarDataset>();
            string genericPath = baseurl + "/{0}q{1}_notes.zip";
            int thisYear = DateTime.Now.Year;
            for (int i = 2009; i <= thisYear-1; i++)
            {
                for (int j = 1; j <= 4; j++)
                {
                    Quarter q = (Quarter)j;

                    EdgarDataset ds = new EdgarDataset
                    {
                        RelativePath = String.Format(genericPath, i.ToString(), j),
                        Year = i,
                        Quarter = q
                    };
                    repository.AddDataset(ds);
                }
            }
            repository.AddDataset(new EdgarDataset { RelativePath = baseurl + "/2017q1_notes.zip", Year = 2017, Quarter = Quarter.QTR1 });
            repository.AddDataset(new EdgarDataset { RelativePath = baseurl + "/2017q2_notes.zip", Year = 2017, Quarter = Quarter.QTR2 });
            repository.AddDataset(new EdgarDataset { RelativePath = baseurl + "/2017q3_notes.zip", Year = 2017, Quarter = Quarter.QTR3 });
        }

        internal static void LoadSECForms(IAnalystRepository repository)
        {
            if (repository.GetSECFormsCount() == 0)
            {
                repository.AddSECForm(new SECForm { Code = "1", Description = "Application for registration or exemption from registration as a national securities exchange (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1.pdf", LastUpddate = "Feb. 1999", SECNumber = "SEC1935", Topic = "Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "1-A", Description = "Regulation A Offering Statement (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1-a.pdf", LastUpddate = "June 2015", SECNumber = "SEC486", Topic = "Securities Act of 1933, Small Businesses" });
                repository.AddSECForm(new SECForm { Code = "1-E", Description = "Notification under Regulation E (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1-e.pdf", LastUpddate = "Aug. 2001", SECNumber = "SEC1807", Topic = "Investment Company Act of 1940, Small Businesses, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "1-K", Description = "Annual Reports and Special Financial Reports (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1-k.pdf", LastUpddate = "June 2015", SECNumber = "SEC2913", Topic = "Securities Act of 1933, Small Businesses" });
                repository.AddSECForm(new SECForm { Code = "1-N", Description = "Form and amendments for notice of registration as a national securities exchange for the sole purpose of trading security futures products (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1-n.pdf", LastUpddate = "Dec. 2013", SECNumber = "SEC2568", Topic = "Securities Exchange Act of 1934, Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "1-SA", Description = "Semiannual Report or Special Financial Report Pursuant to Regulation A (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1-sa.pdf", LastUpddate = "June 2015", SECNumber = "SEC2914", Topic = "Securities Act of 1933, Small Businesses" });
                repository.AddSECForm(new SECForm { Code = "1-U", Description = "Current Report Pursuant to Regulation A (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1-u.pdf", LastUpddate = "June 2015", SECNumber = "SEC2915", Topic = "Securities Act of 1933, Small Businesses" });
                repository.AddSECForm(new SECForm { Code = "1-Z", Description = "Exit Report Under Regulation A (PDF) ", LinkToPdf = "https://www.sec.gov/files/form1-z.pdf", LastUpddate = "June 2015", SECNumber = "SEC2916", Topic = "Securities Act of 1933, Small Businesses" });
                repository.AddSECForm(new SECForm { Code = "2-E", Description = "Report of sales pursuant to Rule 609 of Regulation E (PDF) ", LinkToPdf = "https://www.sec.gov/files/form2-e.pdf", LastUpddate = "Oct. 2006", SECNumber = "SEC1808", Topic = "Investment Company Act of 1940, Small Businesses, Investment Companies" });
                //repository.AddSECForm(new SECForm { Code = "3", Description = "Initial statement of beneficial ownership of securities (PDF) ", LinkToPdf = "https://www.sec.gov/files/form3.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC1473", Topic = "Directors, Officers, Securities Exchange Act of 1934, Significant Shareholders" });
                repository.AddSECForm(new SECForm { Code = "3", Description = "Initial statement of beneficial ownership of securities - general instructions (PDF) ", LinkToPdf = "https://www.sec.gov/files/form3data.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC1472", Topic = "Directors, Officers, Securities Exchange Act of 1934, Significant Shareholders" });
                //repository.AddSECForm(new SECForm { Code = "4", Description = "Statement of changes in beneficial ownership of securities (PDF) ", LinkToPdf = "https://www.sec.gov/files/form4.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC1474", Topic = "Directors, Officers, Securities Exchange Act of 1934, Significant Shareholders" });
                repository.AddSECForm(new SECForm { Code = "4", Description = "Statement of changes in beneficial ownership of securities - general instructions (PDF) ", LinkToPdf = "https://www.sec.gov/files/form4data%2C0.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC1475", Topic = "Directors, Officers, Securities Exchange Act of 1934, Significant Shareholders" });
                //repository.AddSECForm(new SECForm { Code = "5", Description = "Annual statement of changes in beneficial ownership of securities (PDF) ", LinkToPdf = "https://www.sec.gov/files/form5.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC2270T", Topic = "Directors, Officers, Securities Exchange Act of 1934, Significant Shareholders" });
                repository.AddSECForm(new SECForm { Code = "5", Description = "Annual statement of changes in beneficial ownership of securities - general instructions (PDF) ", LinkToPdf = "https://www.sec.gov/files/form5data%2C0.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC2270", Topic = "Directors, Officers, Securities Exchange Act of 1934, Significant Shareholders" });
                repository.AddSECForm(new SECForm { Code = "6-K", Description = "Report of foreign private issuer pursuant to Rule 13a-16 or 15d-16 under the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/form6-k.pdf", LastUpddate = "April 2009", SECNumber = "SEC1815", Topic = "Securities Exchange Act of 1934, International" });
                repository.AddSECForm(new SECForm { Code = "7-M", Description = "Irrevocable Appointment of Agent for Service of Process, Pleadings and Other Papers by Individual Non-Resident Broker or Dealer (PDF) ", LinkToPdf = "https://www.sec.gov/files/form7-m%2C0.pdf", LastUpddate = "June 2012", SECNumber = "SEC876", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "8-A", Description = "Registration of certain classes of securities pursuant to Section 12(b) or (g) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form8-a.pdf", LastUpddate = "June 2015", SECNumber = "SEC1922", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "8-K", Description = "Current report pursuant to Section 13 or 15(d) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form8-k.pdf", LastUpddate = "April 2017", SECNumber = "SEC873", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "8-M", Description = "Irrevocable Appointment of Agent for Service of Process, Pleadings and Other Papers by Corporate Non-Resident Broker or Dealer (PDF) ", LinkToPdf = "https://www.sec.gov/files/form8-m%2C0.pdf", LastUpddate = "June 2012", SECNumber = "SEC877", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "9-M", Description = "Irrevocable Appointment of Agent for Service of Process, Pleadings and Other Papers by Partnership Non-Resident Broker or Dealer (PDF) ", LinkToPdf = "https://www.sec.gov/files/form9-m%2C0.pdf", LastUpddate = "June 2012", SECNumber = "SEC878", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "10", Description = "General form for registration of securities pursuant to Section 12(b) or (g) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form10.pdf", LastUpddate = "Feb. 2008", SECNumber = "SEC1396", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "10-D", Description = "Asset-Backed Issuer Distribution Report Pursuant to Section 13 or 15(d) of the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/form10-d.pdf", LastUpddate = "July 2016", SECNumber = "SEC2503", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "10-K", Description = "Annual report pursuant to Section 13 or 15(d) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form10-k.pdf", LastUpddate = "Nov. 2014", SECNumber = "SEC1673", Topic = "Form 10-K, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "10-M", Description = "Irrevocable Appointment of Agent for Service of Process, Pleadings and Other Papers by Non-Resident General Partner of Broker or Dealer (PDF) ", LinkToPdf = "https://www.sec.gov/files/form10-m%2C0.pdf", LastUpddate = "June 2012", SECNumber = "SEC878", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "10-Q", Description = "General form for quarterly reports under Section 13 or 15(d) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form10-q.pdf", LastUpddate = "Jan. 2012", SECNumber = "SEC1296", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "11-K", Description = "Annual reports of employee stock purchase, savings and similar plans pursuant to Section 15(d) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form11-k.pdf", LastUpddate = "Feb. 2008", SECNumber = "SEC617", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "12b-25", Description = "Notification of late filing (PDF) ", LinkToPdf = "https://www.sec.gov/files/form12b-25%2C0.pdf", LastUpddate = "April 2009", SECNumber = "SEC1344", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "13F", Description = "Information required of institutional investment managers pursuant to Section 13(f) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form13f%2C0.pdf", LastUpddate = "Jan. 2012", SECNumber = "SEC1685", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "13H", Description = "Information Required of Large Traders Pursuant To Section 13(h) of the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/form13h.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC2858", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "15", Description = "Certification and notice of termination of registration under Section 12(g) or suspension of duty to file reports under Sections 13 and 15(d) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form15.pdf", LastUpddate = "Feb. 2008", SECNumber = "SEC2069", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "15F", Description = "Certification of a foreign private issuer’s termination of registration of a class of securities under Section 12(g) or its termination of the duty to file reports under Section 13(a) or Section 15(d) (PDF) ", LinkToPdf = "https://www.sec.gov/files/form15f.pdf", LastUpddate = "Jan. 2014", SECNumber = "", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "17-H", Description = "Risk Assessment for Brokers & Dealers (PDF) ", LinkToPdf = "https://www.sec.gov/files/form17-h.pdf", LastUpddate = "Jan. 2010", SECNumber = "SEC2332", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "18", Description = "Application for registration pursuant to Section 12(b) & (c) of the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/form18.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC1421", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "18-K", Description = "Annual report for foreign governments and political subdivisions thereof (PDF) ", LinkToPdf = "https://www.sec.gov/files/form18-k.pdf", LastUpddate = "April 2007", SECNumber = "SEC1797", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "19b-4", Description = "Proposed rule change by self-regulatory organization (PDF) ", LinkToPdf = "https://www.sec.gov/files/form19b-4.pdf", LastUpddate = "Jan. 2013", SECNumber = "SEC1832", Topic = "Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "19b-4(e)", Description = "Information required of a self-regulatory organization listing and trading a new derivative securities product pursuant to Rule 19b-4(e) under the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/form19b-4e.pdf", LastUpddate = "July 2013", SECNumber = "SEC2449", Topic = "Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "19b-7", Description = "Proposed rule change by self-regulatory organization (PDF) ", LinkToPdf = "https://www.sec.gov/files/form19b-7.pdf", LastUpddate = "July 2007", SECNumber = "SEC2450", Topic = "Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "20-F", Description = "Registration statement / Annual report / Transition report (PDF) ", LinkToPdf = "https://www.sec.gov/files/form20-f.pdf", LastUpddate = "April 2017", SECNumber = "SEC1852", Topic = "Securities Exchange Act of 1934, International" });
                repository.AddSECForm(new SECForm { Code = "24F-2", Description = "Annual notice of securities sold pursuant to Rule 24-f2 (PDF) ", LinkToPdf = "https://www.sec.gov/files/form24f-2.pdf", LastUpddate = "June 2002", SECNumber = "SEC2393", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "25", Description = "Notification of the removal from listing and registration of matured, redeemed or retired securities (PDF) ", LinkToPdf = "https://www.sec.gov/files/form25.pdf", LastUpddate = "March 2006", SECNumber = "SEC1654", Topic = "Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "40-F", Description = "Registration statement pursuant to Section 12 or annual report pursuant to Section 13(a) or 15(d) (PDF)", LinkToPdf = "https://www.sec.gov/files/form40-f.pdf", LastUpddate = "April 2017", SECNumber = "SEC2285", Topic = "Securities Exchange Act of 1934, International" });
                repository.AddSECForm(new SECForm { Code = "144", Description = "Notice of proposed sale of securities pursuant to Rule 144 (PDF) ", LinkToPdf = "https://www.sec.gov/files/form144.pdf", LastUpddate = "Aug. 2007", SECNumber = "SEC1147", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "ABS DD-15E", Description = "Certification of Provider of Third-Party Due Diligence Services for Asset-Backed Securities (PDF) ", LinkToPdf = "https://www.sec.gov/files/formabs-dd-15e.pdf", LastUpddate = "June 2015", SECNumber = "SEC2917", Topic = "Form ABS Due Diligence-15E, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "ABS-15G", Description = "Asset-Backed Securitizer Report (PDF) ", LinkToPdf = "https://www.sec.gov/files/formabs-15g.pdf", LastUpddate = "June 2015", SECNumber = "SEC2860", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "ABS-EE", Description = "Form for Submission of Electronic Exhibits for Asset-Backed Securities (PDF) ", LinkToPdf = "https://www.sec.gov/files/formabs-ee.pdf", LastUpddate = "Nov. 2014", SECNumber = "SEC2910", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "ADV", Description = "Uniform Application for Investment Adviser Registration and Report by Exempt Reporting Advisers (PDF) ", LinkToPdf = "https://www.sec.gov/files/formadv.pdf", LastUpddate = "Oct. 2017", SECNumber = "SEC1707", Topic = "Investment Advisers Act of 1940, Investment Advisers" });
                repository.AddSECForm(new SECForm { Code = "ADV-E", Description = "Certificate of accounting of client securities and funds in the possession or custody of an investment adviser (PDF) ", LinkToPdf = "https://www.sec.gov/files/formadv-e.pdf", LastUpddate = "Jan. 2013", SECNumber = "SEC2223", Topic = "Investment Advisers Act of 1940, Investment Advisers" });
                repository.AddSECForm(new SECForm { Code = "ADV-H", Description = "Application for a temporary or continuing hardship exemption (PDF) ", LinkToPdf = "https://www.sec.gov/files/formadv-h.pdf", LastUpddate = "Sept. 2011", SECNumber = "SEC2566", Topic = "Investment Advisers Act of 1940, Investment Advisers" });
                repository.AddSECForm(new SECForm { Code = "ADV-NR", Description = "Appointment of agent for service of process by non-resident general partner and non-resident managing agent of an investment adviser (PDF) ", LinkToPdf = "https://www.sec.gov/files/formadv-nr.pdf", LastUpddate = "Sept. 2011", SECNumber = "SEC2565", Topic = "Investment Advisers Act of 1940, Investment Advisers" });
                repository.AddSECForm(new SECForm { Code = "ADV-W", Description = "Notice of withdrawal from registration as investment adviser (PDF) ", LinkToPdf = "https://www.sec.gov/files/formadv-w.pdf", LastUpddate = "Nov. 2010", SECNumber = "SEC777", Topic = "Investment Advisers Act of 1940, Investment Advisers" });
                repository.AddSECForm(new SECForm { Code = "ATS", Description = "Initial operation report, amendment to initial operation report and cessation of operations report for alternative trading systems (PDF) ", LinkToPdf = "https://www.sec.gov/files/formats.pdf", LastUpddate = "38473", SECNumber = "SEC2550", Topic = "Alternative Trading Systems" });
                repository.AddSECForm(new SECForm { Code = "ATS-R", Description = "Quarterly report of alternative trading systems activities (PDF) ", LinkToPdf = "https://www.sec.gov/files/formats-r.pdf", LastUpddate = "June 2009", SECNumber = "SEC2551", Topic = "Alternative Trading Systems" });
                repository.AddSECForm(new SECForm { Code = "BD", Description = "Uniform application for broker-dealer registration (PDF) ", LinkToPdf = "https://www.sec.gov/files/formbd.pdf", LastUpddate = "Jan. 2008", SECNumber = "SEC1490", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "BD-N", Description = "Notice of registration as a broker-dealer for the purpose of trading security futures products pursuant to Section 15(b)(11) of the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formbd-n.pdf", LastUpddate = "Jan. 2008", SECNumber = "SEC1500", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "BDW", Description = "Uniform request for broker-dealer withdrawal (PDF) ", LinkToPdf = "https://www.sec.gov/files/formbdw.pdf", LastUpddate = "April 2007", SECNumber = "SEC122", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "C", Description = "Form C (PDF) ", LinkToPdf = "https://www.sec.gov/files/formc.pdf", LastUpddate = "April 2017", SECNumber = "SEC 2930", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "CA-1", Description = "Registration or exemption from registration as a clearing agency and for amendment to registration (PDF) ", LinkToPdf = "https://www.sec.gov/files/formca-1.pdf", LastUpddate = "Oct. 2002", SECNumber = "SEC1853", Topic = "Clearing Agencies" });
                repository.AddSECForm(new SECForm { Code = "CB", Description = "Tender offer/rights offering notification form (PDF) ", LinkToPdf = "https://www.sec.gov/files/formcb.pdf", LastUpddate = "Dec. 2008", SECNumber = "SEC2560", Topic = "Proxy and Tender Offer, Securities Act of 1933, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "CFPORTAL", Description = "Application or Amendment to Application for Registration or Withdrawal from Registration as Funding Portal Under the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formcfportal.pdf", LastUpddate = "Oct. 2015", SECNumber = "", Topic = "Funding Portal, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "D", Description = "Notice of Exempt Offering of Securities ", LinkToPdf = "https://www.sec.gov/info/smallbus/cfformd.htm#", LastUpddate = "March 2009", SECNumber = "SEC1972", Topic = "Securities Act of 1933, Small Businesses" });
                repository.AddSECForm(new SECForm { Code = "F-1", Description = "Registration statement for securities of certain foreign private issuers (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-1.pdf", LastUpddate = "April 2017", SECNumber = "SEC1981", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-3", Description = "Registration statement for securities of certain foreign private issuers (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-3.pdf", LastUpddate = "April 2017", SECNumber = "SEC1983", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-4", Description = "Registration statement for securities of certain foreign private issuers issued in certain business combination transactions (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-4.pdf", LastUpddate = "April 2017", SECNumber = "SEC2078", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-6", Description = "Registration statement under the Securities Act of 1933 for depositary shares evidenced by American depositary receipts (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-6.pdf", LastUpddate = "Oct. 2008", SECNumber = "SEC2001", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-7", Description = "Registration statement under the Securities Act of 1933 for securities of certain Canadian issuers offered for cash upon the exercise of rights granted to existing security holders (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-7.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC2289", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-8", Description = "Registration statement under the Securities Act of 1933 for securities of certain Canadian issuers to be issued in exchange offers or a business combination (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-8.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC2290", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-10", Description = "Registration statement for securities of certain Canadian issuers (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-10.pdf", LastUpddate = "Dec. 2013", SECNumber = "SEC2292", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-80", Description = "Registration statement for securities of certain Canadian issuers to be issued in exchange offers or a business combination (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-80.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC2282", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "F-N", Description = "Appointment of agent for service of process by foreign banks and foreign insurance companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-n.pdf", LastUpddate = "Oct. 2006", SECNumber = "SEC2306", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "F-X", Description = "Appointment of agent for service of process and undertaking (PDF) ", LinkToPdf = "https://www.sec.gov/files/formf-x.pdf", LastUpddate = "Feb. 2008", SECNumber = "SEC2288", Topic = "Securities Act of 1933, International" });
                repository.AddSECForm(new SECForm { Code = "ID", Description = "Uniform application for access codes to file on EDGAR ", LinkToPdf = "https://www.sec.gov/about/forms/formid.html#", LastUpddate = "Dec. 2013", SECNumber = "SEC2084", Topic = "Securities Act of 1933, Securities Exchange Act of 1934, EDGAR Filers" });
                repository.AddSECForm(new SECForm { Code = "MA", Description = "Application for Municipal Advisor Registration; Annual Update of Municipal Advisor Registration; and Amendment of a Prior Application for Registration (PDF) ", LinkToPdf = "https://www.sec.gov/files/formma.pdf", LastUpddate = "April 2014", SECNumber = "SEC2898", Topic = "Securities Exchange Act of 1934, Municipal Advisors" });
                //repository.AddSECForm(new SECForm { Code = "MA", Description = "Instructions for the Form MA Series (PDF) ", LinkToPdf = "https://www.sec.gov/files/2017-03/formmadata.pdf", LastUpddate = "Sept. 2013", SECNumber = "", Topic = "Securities Exchange Act of 1934, Municipal Advisors" });
                repository.AddSECForm(new SECForm { Code = "MA-I", Description = "Information Regarding Natural Persons who Engage in Municipal Advisory Activities (PDF) ", LinkToPdf = "https://www.sec.gov/files/formma-i.pdf", LastUpddate = "April 2017", SECNumber = "SEC2899", Topic = "Securities Exchange Act of 1934, Municipal Advisors" });
                repository.AddSECForm(new SECForm { Code = "MA-NR", Description = "Designation of U.S. Agent for Service of Process for Non-Residents (PDF) ", LinkToPdf = "https://www.sec.gov/files/formma-nr.pdf", LastUpddate = "April 2014", SECNumber = "SEC2900", Topic = "Securities Exchange Act of 1934, Municipal Advisors" });
                repository.AddSECForm(new SECForm { Code = "MA-W", Description = "Notice of Withdrawal from Registration as a Municipal Advisor (PDF) ", LinkToPdf = "https://www.sec.gov/files/formma-w.pdf", LastUpddate = "April 2014", SECNumber = "SEC2901", Topic = "Securities Exchange Act of 1934, Municipal Advisors" });
                repository.AddSECForm(new SECForm { Code = "MSD", Description = "Application for registration as a municipal securities dealer or amendment to such application (PDF) ", LinkToPdf = "https://www.sec.gov/files/formmsd.pdf", LastUpddate = "Dec. 2013", SECNumber = "SEC1534", Topic = "Municipal Securities" });
                repository.AddSECForm(new SECForm { Code = "MSDW", Description = "Notice of withdrawal from registration as a municipal securities dealer (PDF) ", LinkToPdf = "https://www.sec.gov/files/formmsdw.pdf", LastUpddate = "Dec. 2013", SECNumber = "SEC1588", Topic = "Municipal Securities" });
                repository.AddSECForm(new SECForm { Code = "N-1A", Description = "Registration form for open-end management investment companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-1a.pdf", LastUpddate = "Aug. 2017", SECNumber = "SEC2052", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-2", Description = "Registration statement for closed-end management investment companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-2.pdf", LastUpddate = "April 2015", SECNumber = "SEC1716", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-3", Description = "Registration statement of separate accounts organized as management investment companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-3.pdf", LastUpddate = "Aug. 2017", SECNumber = "SEC2124", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-4", Description = "Registration statement of separate accounts organized as unit investment trusts (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-4.pdf", LastUpddate = "Nov. 2009", SECNumber = "SEC2125", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-5", Description = "Registration statement of small business investment company (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-5.pdf", LastUpddate = "March 2010", SECNumber = "SEC993", Topic = "Investment Company Act of 1940, Small Businesses, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-6", Description = "Registration statement for separate accounts organized as unit investment trusts that offer variable life insurance policies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-6.pdf", LastUpddate = "Aug. 2006", SECNumber = "SEC2567", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-6EI-1", Description = "Notification of claim of exemption pursuant to Rule 6e-2 or 6e-3(T) under the Investment Company Act of 1940 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-6e1-1.pdf", LastUpddate = "March 2003", SECNumber = "SEC1130", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-6F", Description = "Notice of intent to elect to be subject to Sections 55-65 of the Investment Company Act of 1940 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-6f.pdf", LastUpddate = "March 2001", SECNumber = "SEC1936", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-8A", Description = "Notification of registration filed pursuant to Section 8(a) of Investment Company Act of 1940 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-8a%2C0.pdf", LastUpddate = "Dec. 2001", SECNumber = "SEC1102", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-8B-2", Description = "Registration statement of unit investment trusts which are currently issuing securities (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-8b-2.pdf", LastUpddate = "March 2010", SECNumber = "SEC977", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-8B-4", Description = "Registration statement of face-amount certificate companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-8b-4.pdf", LastUpddate = "Nov. 2005", SECNumber = "SEC1285", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-8F", Description = "Application for deregistration of certain registered investment companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-8f.pdf", LastUpddate = "Sept. 2010", SECNumber = "SEC1691", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-14", Description = "Form for the registration of securities issued in business combination transactions by investment companies and business development companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-14.pdf", LastUpddate = "July 2013", SECNumber = "SEC2106", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-17D-1", Description = "Report filed by small business investment company (SBIC) (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-17d-1.pdf", LastUpddate = "Aug. 2005", SECNumber = "SEC1839", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-17f-1", Description = "Certificate of accounting of securities and similar investments of a management investment company in the custody of members of national securities exchanges (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-17f-1.pdf", LastUpddate = "Nov. 2003", SECNumber = "SEC2205", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-17f-2", Description = "Certificate of accounting of securities and similar investments in the custody of management investment companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-17f-2.pdf", LastUpddate = "April 2009", SECNumber = "SEC2198", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-18f-1", Description = "Notification of election pursuant to Rule 18f-1 under the Investment Company Act of 1940 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-18f-1.pdf", LastUpddate = "Jan. 2012", SECNumber = "SEC1846", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-23c-3", Description = "Notification of repurchase offer (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-23c-3.pdf", LastUpddate = "Oct. 2003", SECNumber = "SEC2380", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-27D-1", Description = "Accounting of Segregated Trust Account (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-27d-1.pdf", LastUpddate = "April 2014", SECNumber = "SEC1840", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-54A", Description = "Notification of election to be subject to Sections 55-65 of the Investment Company Act of 1940 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-54a.pdf", LastUpddate = "Oct. 2003", SECNumber = "SEC1937", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-54C", Description = "Notification of withdrawal of election to be subject to Sections 55-65 of the Investment Company Act of 1940 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-54c.pdf", LastUpddate = "March 2001", SECNumber = "SEC1938", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-CR", Description = "Current Report, Money Market Fund Material Events (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-cr.pdf", LastUpddate = "Jan. 2015", SECNumber = "SEC2918", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-CSR", Description = "Certified shareholder report of registered management investment companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-csr.pdf", LastUpddate = "Oct. 2017", SECNumber = "SEC2569", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-MFP", Description = "Monthly Schedule of Portfolio Holdings of Money Market Funds (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-mfp.pdf", LastUpddate = "June 2016", SECNumber = "SEC2847", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-PX", Description = "Annual Report of Proxy Voting Record of Registered Management Investment Company (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-px.pdf", LastUpddate = "April 2003", SECNumber = "SEC2451", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-Q", Description = "Quarterly Schedule of Portfolio Holdings of Registered Management Investment Company (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-q.pdf", LastUpddate = "Aug. 2005", SECNumber = "SEC2455", Topic = "Investment Company Act of 1940, Investment Companies" });
                repository.AddSECForm(new SECForm { Code = "N-SAR", Description = "Semi-annual report of registered investment companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/formn-sar.pdf", LastUpddate = "Oct. 2010", SECNumber = "SEC2100", Topic = "Investment Company Act of 1940, Investment Companies" });
                //repository.AddSECForm(new SECForm { Code = "NRSRO", Description = "Form NRSRO - April 2009 Instructions (PDF) ", LinkToPdf = "https://www.sec.gov/files/2017-03/formnrsro-2009-instructions.pdf", LastUpddate = "April 2009", SECNumber = "", Topic = "NRSRO" });
                repository.AddSECForm(new SECForm { Code = "NRSRO", Description = "Application for Registration as a Nationally Recognized Statistical Rating Organization (NRSRO) (PDF) ", LinkToPdf = "https://www.sec.gov/files/2017-02/formnrsro.pdf", LastUpddate = "April 2015", SECNumber = "SEC1541", Topic = "NRSRO" });
                repository.AddSECForm(new SECForm { Code = "PF", Description = "Reporting Form for Investment Advisers to Private Funds and Certain Commodity Pool Operators and Commodity Trading Advisors (PDF) ", LinkToPdf = "https://www.sec.gov/files/formpf.pdf", LastUpddate = "July 2014", SECNumber = "SEC2048", Topic = "Investment Advisers Act of 1940, Investment Advisers" });
                repository.AddSECForm(new SECForm { Code = "PILOT", Description = "Initial operation report, amendment to initial operation report and quarterly report for pilot trading systems operated by self-regulatory organizations (PDF) ", LinkToPdf = "https://www.sec.gov/files/formpilot.pdf", LastUpddate = "Sept. 2013", SECNumber = "SEC2552", Topic = "Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "R31", Description = "Form for Reporting Covered Sales and Covered Round Turn Transactions Under Section 31 of the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formr31.pdf", LastUpddate = "Sept. 2013", SECNumber = "SEC2502", Topic = "Securities Exchange Act of 1934, Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "S-1", Description = "Registration statement under Securities Act of 1933 (PDF) ", LinkToPdf = "https://www.sec.gov/files/forms-1.pdf", LastUpddate = "April 2017", SECNumber = "SEC870", Topic = "Securities Act of 1933, Small Businesses" });
                repository.AddSECForm(new SECForm { Code = "S-3", Description = "Registration statement under Securities Act of 1933 (PDF) ", LinkToPdf = "https://www.sec.gov/files/forms-3.pdf", LastUpddate = "April 2017", SECNumber = "SEC1379", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "S-4", Description = "Registration statement under Securities Act of 1933 (PDF) ", LinkToPdf = "https://www.sec.gov/files/forms-4.pdf", LastUpddate = "April 2017", SECNumber = "SEC2077", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "S-6", Description = "Registration under 1933 act of securities of unit investment trusts registered on form N-8B-2 (PDF) ", LinkToPdf = "https://www.sec.gov/files/forms-6.pdf", LastUpddate = "Jan. 2008", SECNumber = "SEC649", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "S-8", Description = "Registration statement under Securities Act of 1933 to be offered to employees pursuant to certain plans (PDF) ", LinkToPdf = "https://www.sec.gov/files/forms-8.pdf", LastUpddate = "April 2017", SECNumber = "SEC1398", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "S-11", Description = "Registration of securities of certain real estate companies (PDF) ", LinkToPdf = "https://www.sec.gov/files/forms-11.pdf", LastUpddate = "April 2017", SECNumber = "SEC907", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "S-20", Description = "Registration statement under the Securities Act of 1933 (PDF) ", LinkToPdf = "https://www.sec.gov/files/forms-20%2C0.pdf", LastUpddate = "June 2005", SECNumber = "SEC2013", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "SBSE", Description = "Application for Registration of Security-based Swap Dealers and Major Security-based Swap Participants (PDF) ", LinkToPdf = "https://www.sec.gov/files/form-sbse.pdf", LastUpddate = "Jan. 2016", SECNumber = "SEC2924", Topic = "Dodd-Frank Act of 2010, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "SBSE-A", Description = "Application for Registration of Security-based Swap Dealers and Major Security-based Swap Participants that are Registered or Registering with the Commodity Futures Trading Commission as a Swap Dealer (PDF) ", LinkToPdf = "https://www.sec.gov/files/formsbse-a.pdf", LastUpddate = "Jan. 2016", SECNumber = "SEC2925", Topic = "Dodd-Frank Act of 2010, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "SBSE-BD", Description = "Application for Registration of Security-based Swap Dealers and Major Security-based Swap Participants that are Registered Broker-dealers (PDF) ", LinkToPdf = "https://www.sec.gov/files/formsbse-bd.pdf", LastUpddate = "Jan. 2016", SECNumber = "SEC2926", Topic = "Dodd-Frank Act of 2010, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "SBSE-C", Description = "Certifications for Registration of Security-based Swap Dealers and Major Security-based Swap Participants (PDF) ", LinkToPdf = "https://www.sec.gov/files/formsbse-c.pdf", LastUpddate = "Jan. 2016", SECNumber = "SEC2927", Topic = "Dodd-Frank Act of 2010, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "SBSE-W", Description = "Request for Withdrawal from Registration as a Security-based Swap Dealer or Major Security-based Swap Participant (PDF) ", LinkToPdf = "https://www.sec.gov/files/formsbse-w.pdf", LastUpddate = "Jan. 2016", SECNumber = "SEC2928", Topic = "Dodd-Frank Act of 2010, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "SCI", Description = "Systems Compliance and Integrity (PDF) ", LinkToPdf = "https://www.sec.gov/files/form-sci.pdf", LastUpddate = "Sept. 2015", SECNumber = "SEC 2919", Topic = "Securities Exchange Act of 1934, Self-Regulatory Organizations, Clearing Agencies" });
                repository.AddSECForm(new SECForm { Code = "SD", Description = "Specialized Disclosure Report (PDF) ", LinkToPdf = "https://www.sec.gov/files/formsd.pdf", LastUpddate = "Jan. 2014", SECNumber = "SEC697", Topic = "Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "SDR", Description = "Application or Amendment to Application for Registration or Withdrawal from Registration As Security-Based Swap Data Repository Under the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formsdr.pdf", LastUpddate = "Feb. 2015", SECNumber = "SEC2911", Topic = "Dodd-Frank Act of 2010, SBS Data Repositories, Securities Exchange Act of 1934" });
                repository.AddSECForm(new SECForm { Code = "SE", Description = "Submission of Paper Format Exhibits by Electronic Filers (PDF) ", LinkToPdf = "https://www.sec.gov/files/formse%2C0.pdf", LastUpddate = "Nov. 2011", SECNumber = "SEC2082", Topic = "Securities Act of 1933, Securities Exchange Act of 1934, EDGAR Filers" });
                repository.AddSECForm(new SECForm { Code = "SF-1", Description = "Registration Statement Under the Securities Act of 1933 (PDF) ", LinkToPdf = "https://www.sec.gov/files/2017-03/formsf-1.pdf", LastUpddate = "Nov. 2015", SECNumber = "SEC2908", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "SF-3", Description = "Registration Statement Under the Securities Act of 1933 (PDF) ", LinkToPdf = "https://www.sec.gov/files/2017-03/formsf-3.pdf", LastUpddate = "July 2015", SECNumber = "SEC2909", Topic = "Securities Act of 1933" });
                repository.AddSECForm(new SECForm { Code = "SIP", Description = "Application or amendment to application for registration as securities infomation processor (PDF) ", LinkToPdf = "https://www.sec.gov/files/formsip%2C0.pdf", LastUpddate = "March 2013", SECNumber = "SEC1939", Topic = "Other Forms and Materials" });
                repository.AddSECForm(new SECForm { Code = "T-1", Description = "Statement of eligibility and qualification under the Trust Indenture Act of 1939 of corporations designated to act as trustees (PDF) ", LinkToPdf = "https://www.sec.gov/files/formt-1.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC1836", Topic = "Trust Indenture Act of 1939" });
                repository.AddSECForm(new SECForm { Code = "T-2", Description = "Statement of eligibility under the Trust Indenture Act of 1939 of an individual designated to act as trustee (PDF) ", LinkToPdf = "https://www.sec.gov/files/formt-2.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC1849", Topic = "Trust Indenture Act of 1939" });
                repository.AddSECForm(new SECForm { Code = "T-3", Description = "For applications for qualification of indentures under the Trust Indenture Act of 1939 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formt-3.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC1919", Topic = "Trust Indenture Act of 1939" });
                repository.AddSECForm(new SECForm { Code = "T-4", Description = "Application for exemption filed pursuant to Section 304(c) of the Trust Indenture Act of 1939 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formt-4.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC1920", Topic = "Trust Indenture Act of 1939" });
                repository.AddSECForm(new SECForm { Code = "T-6", Description = "Application under Section 310(a)(1) of the Trust Indenture Act of 1939 for determination of eligibility of a foreign personal to act as institutional trustee (PDF) ", LinkToPdf = "https://www.sec.gov/files/formt-6.pdf", LastUpddate = "Jan. 2007", SECNumber = "SEC2275", Topic = "Trust Indenture Act of 1939" });
                repository.AddSECForm(new SECForm { Code = "TA-1", Description = "Uniform form for registration as a transfer agent and for amendment to registration (PDF) ", LinkToPdf = "https://www.sec.gov/files/formta-1.pdf", LastUpddate = "Dec. 2006", SECNumber = "SEC1528", Topic = "Transfer Agents" });
                repository.AddSECForm(new SECForm { Code = "TA-2", Description = "Form for reporting activities of transfer agents (PDF) ", LinkToPdf = "https://www.sec.gov/files/formta-2%2C0.pdf", LastUpddate = "Aug. 2012", SECNumber = "SEC2113", Topic = "Transfer Agents" });
                repository.AddSECForm(new SECForm { Code = "TA-W", Description = "Notice of withdrawal from registration as transfer agent (PDF) ", LinkToPdf = "https://www.sec.gov/files/formta-w.pdf", LastUpddate = "Dec. 2006", SECNumber = "SEC1669", Topic = "Transfer Agents" });
                repository.AddSECForm(new SECForm { Code = "TCR", Description = "Tip, Complaint, or Referral (PDF) ", LinkToPdf = "https://www.sec.gov/files/formtcr.pdf", LastUpddate = "Aug. 2011", SECNumber = "SEC2850", Topic = "Tips Complaints and Referrals, Whistleblower" });
                repository.AddSECForm(new SECForm { Code = "TH", Description = "Notification of Reliance on Temporary Hardship Exemption (PDF) ", LinkToPdf = "https://www.sec.gov/files/formth%2C0.pdf", LastUpddate = "July 2006", SECNumber = "SEC2348", Topic = "Securities Act of 1933, Securities Exchange Act of 1934, EDGAR Filers" });
                repository.AddSECForm(new SECForm { Code = "WB-APP", Description = "Application for Award for Original Information Submitted Pursuant to Section 21F of the Securities Exchange Act of 1934 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formwb-app.pdf", LastUpddate = "Aug. 2011", SECNumber = "SEC2851", Topic = "Tips Complaints and Referrals, Whistleblower" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Part I", Description = "FOCUS Report, Part I (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_1.pdf", LastUpddate = "April 2003", SECNumber = "SEC1705", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Part II", Description = "FOCUS Report, Part II Instructions (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_22.pdf", LastUpddate = "Feb. 2004", SECNumber = "SEC1695A", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Part II", Description = "FOCUS Report, Part II (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_2.pdf", LastUpddate = "July 2002", SECNumber = "SEC1695", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Part IIA", Description = "FOCUS Report Part IIa (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_2f.pdf", LastUpddate = "Feb. 2003", SECNumber = "SEC1696", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Part IIA", Description = "FOCUS Report Part IIa Instructions (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_2a.pdf", LastUpddate = "April 2002", SECNumber = "SEC1696A", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Part IIB", Description = "FOCUS Report, Part IIb (OTC Derivatives Dealer) (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_2b.pdf", LastUpddate = "March 2012", SECNumber = "SEC2430", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Part III", Description = "FOCUS Report: Information Required of All Brokers and Dealers Pursuant to Rule 17a-5, Part III (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_3.pdf", LastUpddate = "41395", SECNumber = "SEC1410", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-5 Schedule I", Description = "(Financial and Operational Combined Uniform Single) FOCUS Report: Information Required of All Brokers and Dealers Pursuant to Rule 17a-5 (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-5_schedi.pdf", LastUpddate = "41395", SECNumber = "SEC1675", Topic = "Broker-Dealers" });
                repository.AddSECForm(new SECForm { Code = "X-17A-19", Description = "Report of Change in Membership Status (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17a-19.pdf", LastUpddate = "July 2001", SECNumber = "SEC1414", Topic = "Self-Regulatory Organizations" });
                repository.AddSECForm(new SECForm { Code = "X-17F-1A", Description = "Missing/Lost/Stolen/Counterfeit Securities Report (PDF) ", LinkToPdf = "https://www.sec.gov/files/formx-17f-1a.pdf", LastUpddate = "37012", SECNumber = "SEC1666", Topic = "Broker-Dealers" });
            }
        }
    }
}
