use Analyst_Edgar_dev

/*
Errores
id		date					level	logger														Exception																																																																																																																																																																																																																																																																																																									Message
13085	2019-02-18 00:13:01.207	ERROR	EdgarDatasetCalculationService								NULL																																																																																																																																																																																																																																																																																																										Datasetid 201704 -- cal.tsv -- line[470160]: 0000913760-17-000119 3 3 1 CashAndSecuritiesSegregatedUnderOtherRegulations us-gaap/2017 CashAndSecuritiesSegregatedUnderOtherRegulations us-gaap/2017
13086	2019-02-18 00:13:01.210	ERROR	EdgarDatasetCalculationService								Analyst.Domain.Edgar.Exceptions.EdgarLineException: Error in file cal.tsv, line 470160 ---> Analyst.Services.EdgarServices.EdgarDatasetServices.InvalidLineException: Key CashAndSecuritiesSegregatedUnderOtherRegulations|us-gaap/2017 is not present in the Tags dictionary, line number: 470160     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetCalculationService.Parse(List`1 fieldNames, List`1 fields, Int32 lineNumber, DataRow dr, Int32 edgarDatasetId) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetCalculationService.cs:line 74     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetBaseService`1.ProcessFile(ConcurrentBag`1 missing, String fileToProcess, String fieldToUpdate, EdgarTaskState state, String[] allLines, String header, String cacheFolder, String tsvFileName, Boolean processInParallel) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetBaseService.cs:line 53     --- End of inner exception stack trace ---													Datasetid 201704 -- cal.tsv -- line[470160]: Key CashAndSecuritiesSegregatedUnderOtherRegulations|us-gaap/2017 is not present in the Tags dictionary, line number: 470160
13087	2019-02-18 00:13:01.250	ERROR	EdgarDatasetCalculationService								NULL																																																																																																																																																																																																																																																																																																										Datasetid 201704 -- cal.tsv -- line[470161]: 0000913760-17-000119 3 4 1 CashAndSecuritiesSegregatedUnderOtherRegulations us-gaap/2017 CashAndSecuritiesSegregatedUnderOtherRegulations us-gaap/2017
13088	2019-02-18 00:13:01.293	ERROR	EdgarDatasetCalculationService								Analyst.Domain.Edgar.Exceptions.EdgarLineException: Error in file cal.tsv, line 470161 ---> Analyst.Services.EdgarServices.EdgarDatasetServices.InvalidLineException: Key CashAndSecuritiesSegregatedUnderOtherRegulations|us-gaap/2017 is not present in the Tags dictionary, line number: 470161     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetCalculationService.Parse(List`1 fieldNames, List`1 fields, Int32 lineNumber, DataRow dr, Int32 edgarDatasetId) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetCalculationService.cs:line 74     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetBaseService`1.ProcessFile(ConcurrentBag`1 missing, String fileToProcess, String fieldToUpdate, EdgarTaskState state, String[] allLines, String header, String cacheFolder, String tsvFileName, Boolean processInParallel) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetBaseService.cs:line 53     --- End of inner exception stack trace ---													Datasetid 201704 -- cal.tsv -- line[470161]: Key CashAndSecuritiesSegregatedUnderOtherRegulations|us-gaap/2017 is not present in the Tags dictionary, line number: 470161
13089	2019-02-18 00:13:02.887	ERROR	EdgarDatasetCalculationService								NULL																																																																																																																																																																																																																																																																																																										Datasetid 201704 -- cal.tsv -- line[639694]: 0000913760-17-000119 3 1 1 CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation 0000913760-17-000119 CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation 0000913760-17-000119
13090	2019-02-18 00:13:02.960	ERROR	EdgarDatasetCalculationService								Analyst.Domain.Edgar.Exceptions.EdgarLineException: Error in file cal.tsv, line 639694 ---> Analyst.Services.EdgarServices.EdgarDatasetServices.InvalidLineException: Key CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation|0000913760-17-000119 is not present in the Tags dictionary, line number: 639694     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetCalculationService.Parse(List`1 fieldNames, List`1 fields, Int32 lineNumber, DataRow dr, Int32 edgarDatasetId) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetCalculationService.cs:line 74     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetBaseService`1.ProcessFile(ConcurrentBag`1 missing, String fileToProcess, String fieldToUpdate, EdgarTaskState state, String[] allLines, String header, String cacheFolder, String tsvFileName, Boolean processInParallel) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetBaseService.cs:line 53     --- End of inner exception stack trace ---	Datasetid 201704 -- cal.tsv -- line[639694]: Key CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation|0000913760-17-000119 is not present in the Tags dictionary, line number: 639694
13091	2019-02-18 00:13:03.123	ERROR	EdgarDatasetCalculationService								NULL																																																																																																																																																																																																																																																																																																										Datasetid 201704 -- cal.tsv -- line[639695]: 0000913760-17-000119 3 2 1 CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation 0000913760-17-000119 CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation 0000913760-17-000119
13092	2019-02-18 00:13:03.153	ERROR	EdgarDatasetCalculationService								Analyst.Domain.Edgar.Exceptions.EdgarLineException: Error in file cal.tsv, line 639695 ---> Analyst.Services.EdgarServices.EdgarDatasetServices.InvalidLineException: Key CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation|0000913760-17-000119 is not present in the Tags dictionary, line number: 639695     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetCalculationService.Parse(List`1 fieldNames, List`1 fields, Int32 lineNumber, DataRow dr, Int32 edgarDatasetId) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetCalculationService.cs:line 74     at Analyst.Services.EdgarDatasetServices.BulkProcessStrategy.EdgarDatasetBaseService`1.ProcessFile(ConcurrentBag`1 missing, String fileToProcess, String fieldToUpdate, EdgarTaskState state, String[] allLines, String header, String cacheFolder, String tsvFileName, Boolean processInParallel) in D:\Desarrollo\src\FinanceAnalysis.Net\Analyst_sln\Analyst.Services\EdgarServices\EdgarDatasetServices\BulkProcessStrategy\EdgarDatasetBaseService.cs:line 53     --- End of inner exception stack trace ---	Datasetid 201704 -- cal.tsv -- line[639695]: Key CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation|0000913760-17-000119 is not present in the Tags dictionary, line number: 639695
13191	2019-02-18 00:23:44.380	FATAL	Analyst.Services.EdgarDatasetServices.EdgarDatasetService	NULL																																																																																																																																																																																																																																																																																																										Process of cal, text or nums failed, process can't continue

*/

select * from EdgarDatasetTags 
where 1=1
and DatasetId = 201704
and 
	(
		Tag in
		(
		'CashAndSecuritiesSegregatedUnderOtherRegulations', --'us-gaap/2017'--470160
		'CashAndSecuritiesSegregatedUnderOtherRegulations',--'us-gaap/2017'--470161
		'CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation',--'0000913760-17-000119'--639694
		'CashAndSecuritiesSegregatedUnderCommodityExchangeActRegulationExcessFundsInSegregation'--'0000913760-17-000119'--639695
		)
		or Tag like 'CashAndSecuritiesSegregatedUnderOtherRegulation%'
	)